server:
  port       : 8083
  log        : ./log.log
  plugin_dir : ./plugins

  devices:
    - name: lokes_frame
      type: inkpate_10

  photos:
    database: ./photos.db
    photos  : ./photos_cache
    sources:
      - plugin: icloud_shared_album
        opts:
          token: B0TGY8gBYTaBj0
    poll_period: 60


